Repository versatus/versatus, pull requests merged in 2022-11, with the labels that each got.

#78 Add husky setup
  Cargo.toml
Labels: enhancement

#87 Remove unused dependencies across all the codebase
  Cargo.toml
  crates/accountable/Cargo.toml
  crates/block/Cargo.toml
  crates/block/src/lib.rs
  crates/blockchain/Cargo.toml
  crates/commands/Cargo.toml
  crates/ledger/Cargo.toml
  crates/lr_trie/Cargo.toml
  crates/lr_trie/src/lr_trie.rs
  crates/lrdb/Cargo.toml
  crates/mempool/Cargo.toml
  crates/messages/Cargo.toml
  crates/miner/Cargo.toml
  crates/network/Cargo.toml
  crates/network/src/lib.rs
  crates/network/src/types/mod.rs
  crates/node/Cargo.toml
  crates/node/src/node.rs
  crates/node/src/runtime/state_module.rs
  crates/node/src/runtime/swarm.rs
  crates/node/src/runtime/validator_module.rs
  crates/pool/Cargo.toml
  crates/primitives/Cargo.toml
  crates/primitives/src/lib.rs
  crates/state/Cargo.toml
  crates/state/src/lib.rs
  crates/state/tests/node_state.rs
  crates/validator/src/validator_unit.rs
  crates/vrrb_config/Cargo.toml
  crates/vrrb_core/Cargo.toml
  crates/vrrb_core/src/account.rs
  crates/vrrb_lib/Cargo.toml
  crates/wallet/Cargo.toml
Labels: bug, enhancement

#71 Changing trait allowing to get deserialized data from LRTrie ReadHandle to generic.
  crates/lr_trie/src/lr_trie.rs
  crates/validator/src/txn_validator.rs
Labels: bug, enhancement

#82 Integrate Wallet HTTP API into Node
  crates/cli/src/commands/node.rs
  crates/dkg_engine/Cargo.toml
  crates/dkg_engine/src/test_utils.rs
  crates/node/Cargo.toml
  crates/node/src/command_handler.rs
  crates/node/src/lib.rs
  crates/node/src/node.rs
  crates/node/src/node_auth.rs
  crates/node/src/test_utils.rs
  crates/node/tests/node.rs
  crates/vrrb_config/src/lib.rs
  crates/vrrb_core/Cargo.toml
  crates/vrrb_core/src/command_router.rs
  crates/vrrb_core/src/lib.rs
  crates/vrrb_rpc/Cargo.toml
  crates/vrrb_rpc/src/http/mod.rs
Labels: enhancement

#89 Apply clippy fixes to Node API
  crates/lrdb/src/lr_db.rs
  crates/lrdb/src/vrrb_db.rs
  crates/network/src/protocol.rs
  crates/quorum/src/lib.rs
  crates/state/src/components.rs
  crates/vrrb_config/src/lib.rs
Labels: enhancement

#88 feat-syncing-node: Node Syncing POC, version 0 - works
  Cargo.toml
  crates/primitives/src/types/mod.rs
  crates/syncing/Cargo.toml
  crates/syncing/src/bootstrap.rs
  crates/syncing/src/broker.rs
  crates/syncing/src/config.rs
  crates/syncing/src/context.rs
  crates/syncing/src/discovery.rs
  crates/syncing/src/error.rs
  crates/syncing/src/lib.rs
  crates/syncing/src/lrnodepool.rs
  crates/syncing/src/message.rs
  crates/syncing/src/transfer.rs
  infra/config/bootstrap.toml
Labels: enhancement

#100 Update logger settings
  Cargo.toml
  crates/telemetry/src/subscriber.rs
Labels: bug, enhancement

#101 Fix clippy issues
  .cargo-husky/hooks/pre-commit
  .cargo-husky/hooks/pre-push
  .github/workflows/rust.yaml
  crates/claim/src/claim.rs
  crates/primitives/src/types/mod.rs
Labels: enhancement

#80 Feat block rewards
  crates/block/src/block.rs
  crates/block/src/header.rs
  crates/block/src/invalid.rs
  crates/block/src/lib.rs
  crates/blockchain/src/blockchain.rs
  crates/miner/src/miner.rs
  crates/node/src/runtime/swarm.rs
  crates/primitives/src/types/mod.rs
  crates/reward/Cargo.toml
  crates/reward/src/reward.rs
  crates/state/src/components.rs
  crates/state/src/state.rs
  crates/state/src/types.rs
Labels: enhancement

#103 Refactor event router to broadcast events
  crates/vrrb_core/Cargo.toml
  crates/vrrb_core/src/event_router.rs
  crates/vrrb_core/src/result.rs
Labels: bug, enhancement

#105 Temporarily disable brittle test on quorum crate
  crates/quorum/src/lib.rs
Labels: bug

#106 Update Wallet API structure
  crates/node/src/node.rs
  crates/reward/src/reward.rs
  crates/vrrb_rpc/Cargo.toml
  crates/vrrb_rpc/src/http/config.rs
  crates/vrrb_rpc/src/http/mod.rs
  crates/vrrb_rpc/src/http/router.rs
  crates/vrrb_rpc/src/http/routes/accounts.rs
  crates/vrrb_rpc/src/http/routes/health.rs
  crates/vrrb_rpc/src/http/routes/mod.rs
  crates/vrrb_rpc/src/http/server.rs
  crates/vrrb_rpc/src/lib.rs
  crates/vrrb_rpc/tests/common/mod.rs
  crates/vrrb_rpc/tests/http.rs
Labels: bug, enhancement
