Repository versatus/versatus, pull requests merged in 2022-09, with the labels that each got.

#27 Module feature DKG is finished.
  Cargo.toml
  commands/src/command.rs
  dkg_engine/Cargo.toml
  dkg_engine/handler.rs
  dkg_engine/src/dkg.rs
  dkg_engine/src/lib.rs
  dkg_engine/src/test_utils.rs
  dkg_engine/src/types/config.rs
  dkg_engine/src/types/mod.rs
  node/Cargo.toml
  node/src/handler.rs
  node/src/node.rs
Labels: enhancement

#29 Scaffold primitives package to contain basic shared type definitions
  Cargo.toml
  primitives/Cargo.toml
  primitives/src/lib.rs
Labels: documentation, enhancement

#36 Update LR Trie to work with owned byte vectors instead of byte slices
  lr_trie/src/lr_trie.rs
  lr_trie/src/op.rs
  state_trie/src/lib.rs
  tx_trie/src/lib.rs
Labels: bug, enhancement

#30 Add minimal infrastructure setup and placeholder node entrypoint
  .dockerignore
  Cargo.toml
  dkg_engine/Cargo.toml
  infra/docker/Dockerfile
  infra/scripts/run.sh
  node/.gitignore
  node/cli/Cargo.toml
  node/cli/src/cli.rs
  node/cli/src/lib.rs
  node/core/Cargo.toml
  node/core/src/handler.rs
  node/core/src/lib.rs
  node/core/src/node.rs
  node/service/Cargo.toml
  node/service/src/lib.rs
  node/service/src/main.rs
  node/service/src/node_service.rs
  quorum/Cargo.toml
  telemetry/Cargo.toml
  telemetry/src/lib.rs
  telemetry/src/subscriber.rs
  vrrb_lib/Cargo.toml
Labels: enhancement

#49 Set Rust version to latest stable
  rust-toolchain.toml
Labels: enhancement

#53 Run formatter
  dkg_engine/src/types/mod.rs
  ev_mem_pool/src/lib.rs
  messages/src/message.rs
  node/core/src/handler.rs
  primitives/src/lib.rs
  quorum/src/election.rs
  quorum/src/lib.rs
  quorum/src/quorum.rs
  state/src/state.rs
  vrrb_vrf/src/vvrf.rs
  wallet/src/wallet.rs
Labels: bug
