Repository versatus/versatus, pull requests merged in 2022-08, with the labels that each got.

#7 Fixed most of cargo audit issues.
  .github/workflows/rust.yaml
  accountable/Cargo.toml
  block/Cargo.toml
  blockchain/Cargo.toml
  blockchain/src/blockchain.rs
  claim/Cargo.toml
  claim_concept/Cargo.toml
  commands/Cargo.toml
  events/Cargo.toml
  ledger/Cargo.toml
  messages/Cargo.toml
  miner/Cargo.toml
  network/Cargo.toml
  node/Cargo.toml
  noncing/Cargo.toml
  ownable/Cargo.toml
  pool/Cargo.toml
  quorum/Cargo.toml
  reward/Cargo.toml
  state/Cargo.toml
  txn/Cargo.toml
  updateable/Cargo.toml
  validator/Cargo.toml
  verifiable/Cargo.toml
  vrrb_cli/Cargo.toml
  vrrb_gui/Cargo.toml
  vrrb_lib/Cargo.toml
  vrrb_lib/src/utils.rs
  wallet/Cargo.toml
Labels: bug, enhancement

#4 Add left right database
  Cargo.toml
  lrdb/Cargo.toml
  lrdb/src/lib.rs
Labels: enhancement

#12 Added test for simultaneous reads and writes
  lrdb/Cargo.toml
  lrdb/src/lib.rs
  lrdb/src/lr_db.rs
Labels: enhancement

#17 Add Tx mempool
  .github/workflows/run_tests.yml
  Cargo.toml
  claim/src/poc.rs
  mempool/Cargo.toml
  mempool/src/error.rs
  mempool/src/lib.rs
  mempool/src/mempool.rs
  state/src/state.rs
  txn/src/txn.rs
Labels: enhancement

#20 Re-add Tx mempool (#17)
  Cargo.toml
  mempool/Cargo.toml
  mempool/src/error.rs
  mempool/src/lib.rs
  mempool/src/mempool.rs
  txn/src/txn.rs
Labels: enhancement

#24 fix vrf crate warnings
  vrrb_vrf/src/vrng.rs
  vrrb_vrf/src/vvrf.rs
Labels: bug

#21 Update LR Trie API
  lr_trie/Cargo.toml
  lr_trie/src/db.rs
  lr_trie/src/error.rs
  lr_trie/src/inner.rs
  lr_trie/src/lib.rs
  lr_trie/src/lr_trie.rs
  lr_trie/src/nibbles.rs
  lr_trie/src/node.rs
  lr_trie/src/op.rs
  lr_trie/src/result.rs
  lr_trie/src/trie.rs
  state_trie/Cargo.toml
  state_trie/src/lib.rs
  tx_trie/Cargo.toml
  tx_trie/src/lib.rs
Labels: bug, enhancement

#26 Move MPT internals to patriecia lib
  lr_trie/Cargo.toml
  lr_trie/src/db.rs
  lr_trie/src/error.rs
  lr_trie/src/inner.rs
  lr_trie/src/lib.rs
  lr_trie/src/lr_trie.rs
  lr_trie/src/nibbles.rs
  lr_trie/src/node.rs
  lr_trie/src/result.rs
  lr_trie/src/trie.rs
  lrdb/Cargo.toml
  lrdb/src/lib.rs
  lrdb/src/lr_db.rs
  lrdb/src/result.rs
  lrdb/src/vrrb_db.rs
  state_trie/Cargo.toml
  state_trie/src/lib.rs
  tx_trie/Cargo.toml
  tx_trie/src/lib.rs
Labels: enhancement
