Repository versatus/versatus, pull requests merged in 2023-01, with the labels that each got.

#120 Refactor lrdb to use lr_trie and update lr_trie to allow arbitrary non-serialized values to be fed in
  crates/lr_trie/src/inner.rs
  crates/lr_trie/src/inner_wrapper.rs
  crates/lr_trie/src/lib.rs
  crates/lr_trie/src/lr_trie.rs
  crates/lr_trie/src/result.rs
  crates/lr_trie/src/trie.rs
  crates/lrdb/Cargo.toml
  crates/lrdb/src/lib.rs
  crates/lrdb/src/lr_db.rs
  crates/lrdb/src/lrdb.rs
  crates/lrdb/src/result.rs
  crates/lrdb/src/state_db.rs
  crates/lrdb/src/vrrb_db.rs
Labels: enhancement

#119 DKG Engine fixed
  crates/dkg_engine/Cargo.toml
  crates/dkg_engine/src/dkg.rs
  crates/dkg_engine/src/test_utils.rs
  crates/dkg_engine/src/types/mod.rs
  crates/signer/src/signer.rs
Labels: bug

#111 refactor block seed to be generated with vrf crate and use last block hash and theshold sig as payload
  crates/block/Cargo.toml
  crates/block/src/block.rs
  crates/block/src/header.rs
  crates/block/src/invalid.rs
  crates/block/src/lib.rs
  crates/blockchain/src/blockchain.rs
  crates/miner/src/miner.rs
  crates/node/src/runtime/miner.rs
  crates/vrrb_rpc/src/http/routes/accounts.rs
Labels: bug, enhancement

#122 Add tmp_key directory to gitignore
  .gitignore
Labels: bug, enhancement

#123 Update state management engine
  Cargo.toml
  crates/block/src/block.rs
  crates/block/src/header.rs
  crates/block/src/lib.rs
  crates/dkg_engine/src/test_utils.rs
  crates/lrdb/src/lib.rs
  crates/lrdb/src/state_db.rs
  crates/lrdb/src/txn_db.rs
  crates/mempool/src/mempool.rs
  crates/node/Cargo.toml
  crates/node/src/node.rs
  crates/node/src/runtime/broadcast_module.rs
  crates/node/src/runtime/state_module.rs
  crates/node/src/test_utils.rs
  crates/node/tests/rpc_api.rs
  crates/node/tests/startup.rs
  crates/node/tests/state_management.rs
  crates/primitives/src/types.rs
  crates/state/src/node_state.rs
  crates/state/tests/node_state.rs
  crates/state_trie/Cargo.toml
  crates/state_trie/src/lib.rs
  crates/vrrb_config/src/lib.rs
  crates/vrrb_core/Cargo.toml
  crates/vrrb_core/src/event_router.rs
  crates/vrrb_core/src/lib.rs
  crates/vrrb_core/src/txn.rs
  crates/vrrb_rpc/src/rpc/api.rs
Labels: enhancement

#130 Update vrf crate
  crates/block/src/block.rs
  crates/block/src/header.rs
  crates/block/src/lib.rs
  crates/miner/src/miner.rs
Labels: bug, enhancement

#128 Update mempool architecture to accept new transaction structure
  Cargo.toml
  crates/mempool/Cargo.toml
  crates/mempool/src/error.rs
  crates/mempool/src/ev_mem_pool.rs
  crates/mempool/src/lib.rs
  crates/mempool/src/mempool.rs
  crates/mempool/src/pool.rs
  crates/node/Cargo.toml
  crates/node/src/runtime/blockchain_module.rs
  crates/primitives/src/types.rs
  crates/state/Cargo.toml
  crates/state/src/node_state.rs
  crates/validator/src/txn_validator.rs
  crates/vrrb_core/src/helpers.rs
  crates/vrrb_core/src/lib.rs
  crates/vrrb_core/src/serde_helpers.rs
  crates/vrrb_core/src/txn.rs
Labels: bug, enhancement

#133 Chore fix state crate bugs
  crates/block/src/block.rs
  crates/mempool/src/lib.rs
  crates/mempool/src/mempool.rs
  crates/node/src/runtime/state_module.rs
  crates/state/src/node_state.rs
  crates/vrrb_core/src/event_router.rs
Labels: bug

#134 Fix compilation issues on Validator crate
  crates/validator/src/mempool_processor.rs
  crates/validator/src/txn_validator.rs
  crates/validator/src/validator_unit.rs
Labels: bug

#135 Fix styling issues
  crates/block/src/block.rs
  crates/block/src/header.rs
  crates/block/src/lib.rs
  crates/job_pool/src/task.rs
  crates/lr_trie/src/inner.rs
  crates/lr_trie/src/inner_wrapper.rs
  crates/lr_trie/src/lib.rs
  crates/lr_trie/src/trie.rs
  crates/lrdb/src/lib.rs
  crates/lrdb/src/result.rs
  crates/lrdb/src/state_db.rs
  crates/lrdb/src/txn_db.rs
  crates/mempool/src/lib.rs
  crates/miner/src/miner.rs
  crates/network/src/network.rs
  crates/network/src/types/message.rs
  crates/node/src/lib.rs
  crates/node/src/node.rs
  crates/node/src/runtime/broadcast_module.rs
  crates/node/src/runtime/mining_module.rs
  crates/node/src/runtime/state_module.rs
  crates/node/src/runtime/validator_module.rs
  crates/node/tests/startup.rs
  crates/node/tests/state_management.rs
  crates/primitives/src/node.rs
  crates/primitives/src/types.rs
  crates/signer/src/signer.rs
  crates/state/src/node_state.rs
  crates/state/src/state.rs
  crates/storage/src/lib.rs
  crates/validator/src/lib.rs
  crates/validator/src/validator_unit.rs
  crates/vrrb_config/src/lib.rs
  crates/vrrb_core/src/event_router.rs
  crates/vrrb_core/src/keypair.rs
  crates/vrrb_core/src/serde_helpers.rs
  crates/vrrb_core/src/txn.rs
  crates/vrrb_rpc/src/lib.rs
  crates/vrrb_rpc/src/rpc/api.rs
  crates/vrrb_rpc/src/rpc/client.rs
  crates/vrrb_rpc/src/rpc/server.rs
  crates/wallet/src/wallet.rs
Labels: enhancement

#136 Update dependencies on all crates to inherit from workspace
  Cargo.toml
  crates/block/Cargo.toml
  crates/node/Cargo.toml
  crates/vrrb_core/Cargo.toml
Labels: enhancement

#137 Update Miner crate to match protocol
  Cargo.toml
  crates/block/src/block.rs
  crates/block/src/convergence_block.rs
  crates/block/src/genesis.rs
  crates/block/src/header.rs
  crates/block/src/lib.rs
  crates/block/src/proposal_block.rs
  crates/block/src/types.rs
  crates/block/src/vesting.rs
  crates/mempool/src/mempool.rs
  crates/miner/Cargo.toml
  crates/miner/src/lib.rs
  crates/miner/src/miner.rs
  crates/miner/src/miner_v1.rs
  crates/miner/src/result.rs
  crates/node/src/node.rs
  crates/node/src/runtime/state_module.rs
  crates/node/src/storage.rs
  crates/node/tests/node.rs
  crates/node/tests/state_management.rs
  crates/primitives/src/types.rs
  crates/state/Cargo.toml
  crates/state/src/backing_db.rs
  crates/state/src/lib.rs
  crates/state/src/node_state.rs
  crates/state/src/state.rs
  crates/utils/src/lib.rs
  crates/validator/src/mempool_processor.rs
  crates/vrrb_core/src/event_router.rs
  crates/vrrb_core/src/txn.rs
  crates/vrrb_rpc/src/rpc/api.rs
  crates/vrrb_rpc/src/rpc/server.rs
  crates/vrrb_vrf/src/vvrf.rs
Labels: enhancement

#142 Update broken test that depedns on mempool read handle
  crates/mempool/src/lib.rs
Labels: bug

#143 Update validator crate to match protocol
  Cargo.toml
  crates/dkg_engine/src/dkg.rs
  crates/node/src/runtime/validator_module.rs
  crates/primitives/src/types.rs
  crates/validator/Cargo.toml
  crates/validator/src/lib.rs
  crates/validator/src/mempool_processor.rs
  crates/validator/src/result.rs
  crates/validator/src/txn_validator.rs
  crates/validator/src/validator_core.rs
  crates/validator/src/validator_core_manager.rs
  crates/validator/src/validator_unit.rs
Labels: bug, enhancement

#144 Update Node CLI to read or generate key pairs on startup
  .cargo-husky/hooks/pre-commit
  .cargo-husky/hooks/pre-push
  .gitignore
  crates/cli/src/commands/node.rs
  crates/dkg_engine/Cargo.toml
  crates/dkg_engine/src/dkg.rs
  crates/dkg_engine/src/test_utils.rs
  crates/node/src/test_utils.rs
  crates/node/tests/state_management.rs
  crates/node/tests/state_sync.rs
  crates/state/tests/node_state.rs
  crates/vrrb_config/Cargo.toml
  crates/vrrb_config/src/lib.rs
Labels: enhancement
