Repository versatus/versatus, pull requests merged in 2023-05, with the labels that each got.

#309 Fix imports on lr_trie and implement missing trait members
  crates/storage/lr_trie/src/inner_wrapper.rs
  crates/storage/vrrbdb/src/rocksdb_adapter.rs
Labels: bug

#310 Bump Rust to latest minor release
  rust-toolchain.toml
Labels: enhancement

#312 Update len method on trie to accurately reflect total nodes stored in it.
  crates/storage/lr_trie/Cargo.toml
  crates/storage/lr_trie/src/inner.rs
  crates/storage/lr_trie/src/inner_wrapper.rs
  crates/storage/lr_trie/src/trie.rs
Labels: bug, enhancement

#315 Revert "Handle "Mine Proposal" event in harvester; consider individual votes (Yes/No) percentage for certification"
  crates/block/src/proposal_block.rs
  crates/block/src/types.rs
  crates/consensus/dkg_engine/src/types/mod.rs
  crates/consensus/signer/src/signer.rs
  crates/events/src/event.rs
  crates/events/src/event_data.rs
  crates/miner/src/lib.rs
  crates/miner/src/miner.rs
  crates/miner/src/test_helpers.rs
  crates/network/src/network.rs
  crates/node/Cargo.toml
  crates/node/src/runtime/broadcast_module.rs
  crates/node/src/runtime/dag_module.rs
  crates/node/src/runtime/farmer_harvester_module.rs
  crates/node/src/runtime/farmer_module.rs
  crates/node/src/runtime/harvester_module.rs
  crates/node/src/runtime/mining_module.rs
  crates/node/src/runtime/mod.rs
  crates/node/src/services/scheduler.rs
  crates/primitives/src/base.rs
  crates/validator/src/validator_core.rs
  crates/vrrb_core/src/claim.rs
  crates/vrrb_core/src/keypair.rs
  crates/vrrb_core/src/staking.rs
  crates/vrrb_core/src/txn.rs
Labels: bug

#316 Add missing defaults to config builders so test pass
  crates/node/src/test_utils.rs
  crates/vrrb_config/src/lib.rs
Labels: enhancement

#313 Expose and implement methods to update the global state of the network
  Cargo.toml
  crates/cli/src/commands/wallet/mod.rs
  crates/cli/src/commands/wallet/transfer.rs
  crates/events/src/event.rs
  crates/mempool/src/lib.rs
  crates/mempool/src/mempool.rs
  crates/miner/src/lib.rs
  crates/miner/src/test_helpers.rs
  crates/node/src/runtime/broadcast_module.rs
  crates/node/src/runtime/dag_module.rs
  crates/node/src/runtime/dkg_module.rs
  crates/node/src/runtime/election_module.rs
  crates/node/src/runtime/farmer_module.rs
  crates/node/src/runtime/harvester_module.rs
  crates/node/src/runtime/mod.rs
  crates/node/src/runtime/state_module.rs
  crates/node/src/runtime/swarm_module.rs
  crates/node/src/services/scheduler.rs
  crates/node/src/test_utils.rs
  crates/node/tests/block_processing.rs
  crates/node/tests/rpc_api.rs
  crates/node/tests/startup.rs
  crates/node/tests/state_sync.rs
  crates/primitives/src/address.rs
  crates/storage/Cargo.toml
  crates/storage/lr_trie/src/inner.rs
  crates/storage/lr_trie/src/inner_wrapper.rs
  crates/storage/lr_trie/src/trie.rs
  crates/storage/vrrbdb/Cargo.toml
  crates/storage/vrrbdb/src/claim_store/mod.rs
  crates/storage/vrrbdb/src/rocksdb_adapter.rs
  crates/storage/vrrbdb/src/state_store/mod.rs
  crates/storage/vrrbdb/src/state_store/state_store_rh.rs
  crates/storage/vrrbdb/src/transaction_store/mod.rs
  crates/storage/vrrbdb/src/vrrbdb.rs
  crates/storage/vrrbdb/tests/common.rs
  crates/storage/vrrbdb/tests/test_claim_store.rs
  crates/storage/vrrbdb/tests/test_state_store.rs
  crates/validator/src/lib.rs
  crates/validator/src/txn_validator.rs
  crates/vrrb_core/src/account.rs
  crates/vrrb_core/src/txn.rs
  crates/vrrb_grpc/src/node_read.rs
  crates/vrrb_grpc/src/node_write.rs
  crates/vrrb_rpc/src/rpc/api.rs
  crates/vrrb_rpc/tests/rpc.rs
  crates/wallet/src/v2/mod.rs
  crates/wallet/tests/wallet_rpc_tests.rs
Labels: enhancement

#321 Handle Mine Proposal event in harvester runtime module
  crates/block/src/proposal_block.rs
  crates/block/src/types.rs
  crates/consensus/dkg_engine/src/types/mod.rs
  crates/consensus/signer/src/signer.rs
  crates/events/src/event.rs
  crates/events/src/event_data.rs
  crates/miner/src/lib.rs
  crates/miner/src/miner.rs
  crates/miner/src/test_helpers.rs
  crates/network/src/network.rs
  crates/node/Cargo.toml
  crates/node/src/lib.rs
  crates/node/src/runtime/broadcast_module.rs
  crates/node/src/runtime/dag_module.rs
  crates/node/src/runtime/farmer_harvester_module.rs
  crates/node/src/runtime/farmer_module.rs
  crates/node/src/runtime/harvester_module.rs
  crates/node/src/runtime/mining_module.rs
  crates/node/src/runtime/mod.rs
  crates/node/src/runtime/state_module.rs
  crates/node/src/services/scheduler.rs
  crates/node/src/test_utils.rs
  crates/primitives/src/base.rs
  crates/telemetry/src/subscriber.rs
  crates/validator/src/validator_core.rs
  crates/vrrb_core/src/claim.rs
  crates/vrrb_core/src/keypair.rs
  crates/vrrb_core/src/staking.rs
  crates/vrrb_core/src/txn.rs
Labels: enhancement

#326 fix: infinitely recursive function for db state store
  crates/storage/vrrbdb/src/state_store/mod.rs
Labels: bug

#339 Add dyswarm to manifests
  Cargo.toml
  crates/node/Cargo.toml
Labels: enhancement, code quality

#296 CI: Adds `clippy-check@v1`
  .github/workflows/rust.yaml
  crates/miner/src/test_helpers.rs
  crates/node/src/node.rs
  crates/node/src/runtime/farmer_module.rs
  crates/node/src/runtime/mod.rs
Labels: CI

#343 Docs mods
  docs/GettingStarted.md
Labels: documentation
