Repository versatus/versatus, pull requests merged in 2023-11, with the labels that each got.

#621 Add tests and methods for certifying `GenesisBlock` and appending it to DAG
  Cargo.lock
  crates/block/src/convergence_block.rs
  crates/block/src/genesis.rs
  crates/node/src/consensus/consensus_module.rs
  crates/node/src/runtime/handler_helpers.rs
  crates/node/src/runtime/node_runtime.rs
  crates/node/src/runtime/node_runtime_handler.rs
  crates/node/src/state_manager/dag.rs
  crates/node/src/state_manager/manager.rs
  crates/node/tests/genesis_txns.rs
  crates/node/tests/harvesters.rs
Labels: must-have

#634 Update `block` error handling
  crates/block/src/convergence_block.rs
  crates/block/src/error.rs
  crates/block/src/genesis.rs
  crates/block/src/invalid.rs
  crates/block/src/lib.rs
Labels: code quality

#646 Ensure quorum assignment event is broadcast over network properly in order to trigger genesis block generation event.
  crates/node/src/consensus/consensus_event_handler.rs
  crates/node/src/consensus/consensus_module.rs
  crates/node/src/network/handler.rs
  crates/node/src/network/module.rs
  crates/node/src/network/network_event.rs
  crates/node/src/network/network_event_handler.rs
  crates/node/src/node.rs
  crates/node/src/runtime/mod.rs
  crates/node/src/runtime/node_runtime_handler.rs
  crates/node/src/runtime/setup.rs
  crates/node/src/test_utils.rs
  crates/node/tests/block_processing.rs
  examples/multichain.rs
Labels: bug, must-have

#635 Fix readability of nested `if let` expressions in genesis block methods
  crates/node/src/runtime/handler_helpers.rs
  crates/node/src/runtime/node_runtime.rs
  crates/node/src/runtime/node_runtime_handler.rs
  crates/node/src/state_manager/dag.rs
  crates/node/src/state_manager/manager.rs
  crates/node/tests/genesis_txns.rs
  crates/node/tests/harvesters.rs
Labels: code quality

#637 Add serial test attribute to genesis reward tests
  crates/node/tests/genesis_txns.rs
Labels: code quality

#661 Setup manual WASI & add memory ceiling
  crates/wasm_runtime/src/lib.rs
  crates/wasm_runtime/src/limiting_tunables.rs
  crates/wasm_runtime/src/runtime_tests.rs
  crates/wasm_runtime/src/wasm_runtime.rs
Labels: enhancement

#663 Add `wasm_runtime` dependencies to `wasm_cli`
  Cargo.lock
  Cargo.toml
  crates/wasm_cli/Cargo.toml
  crates/wasm_cli/src/commands/execute/mod.rs
Labels: bug

#664 Update `apple_sdk` frameworks for libclang build inputs
  shell.nix
Labels: bug

#667 Add operation metering middleware to `wasm_runtime` and `wasm_cli`
  Cargo.lock
  Cargo.toml
  crates/wasm_cli/src/commands/execute/mod.rs
  crates/wasm_runtime/Cargo.toml
  crates/wasm_runtime/src/lib.rs
  crates/wasm_runtime/src/metering.rs
  crates/wasm_runtime/src/runtime_tests.rs
  crates/wasm_runtime/src/wasm_runtime.rs
Labels: enhancement

#670 Fix compilation errors in `node` and `storage` tests
  crates/cli/tests/whitelist_data/whitelist.json
  crates/node/src/state_manager/mod.rs
  crates/storage/vrrbdb/tests/test_state_store.rs
Labels: bug, CI

#636 Update naming convention for genesis block rewards
  crates/miner/src/miner.rs
  crates/node/src/runtime/mod.rs
  crates/node/tests/genesis_rewards.rs
Labels: code quality

#673 Add whitelist_data/whitelist.json to .gitignore
  .gitignore
Labels: good first issue, code quality, nice-to-have

#671 Feat prometheus base exporter 641
  Cargo.toml
  crates/metric_exporter/Cargo.toml
  crates/metric_exporter/src/examples/metrics_example.rs
  crates/metric_exporter/src/lib.rs
  crates/metric_exporter/src/metric_factory.rs
  crates/metric_exporter/src/render.rs
Labels: enhancement

#674 Fix Serialization and Deserialization on Address
  crates/primitives/src/address.rs
Labels: bug, enhancement, must-have

#677 Refactor panics from entries method on stores within storage crate.
  crates/node/src/runtime/handler_helpers.rs
  crates/node/src/runtime/node_runtime.rs
  crates/node/src/runtime/node_runtime_handler.rs
  crates/node/src/state_manager/manager.rs
  crates/node/src/state_reader.rs
  crates/node/src/test_utils.rs
  crates/storage/vrrbdb/src/claim_store/claim_store_rh.rs
  crates/storage/vrrbdb/src/state_store/state_store_rh.rs
  crates/storage/vrrbdb/src/transaction_store/transaction_store_rh.rs
  crates/storage/vrrbdb/src/vrrbdb_read_handle.rs
  crates/vrrb_rpc/src/rpc/server_impl.rs
Labels: bug, enhancement

#681 `vrrb_rpc` general cleanup
  Cargo.lock
  crates/vrrb_rpc/src/http/config.rs
  crates/vrrb_rpc/src/http/routes/accounts.rs
  crates/vrrb_rpc/src/http/server.rs
  crates/vrrb_rpc/src/rpc/api.rs
  crates/vrrb_rpc/src/rpc/server_impl.rs
  crates/vrrb_rpc/tests/rpc.rs
Labels: code quality

#613 Fix clippy warnings for node crate (2/3)
  crates/node/src/consensus/consensus_module.rs
  crates/node/src/consensus/quorum_module.rs
  crates/node/src/mining_module.rs
  crates/node/src/network/component.rs
  crates/node/src/network/module.rs
  crates/node/src/runtime/handler_helpers.rs
  crates/node/src/runtime/node_runtime.rs
  crates/node/src/runtime/node_runtime_handler.rs
  crates/node/src/state_manager/dag.rs
  crates/node/src/state_manager/manager.rs
  crates/node/src/state_manager/utils.rs
  crates/node/src/test_utils.rs
Labels: code quality

#627 Update formatter features in `.rustfmt.toml`
  .rustfmt.toml
Labels: code quality

#685 Update rust version to 1.74
  rust-toolchain.toml
Labels: code quality

#684 Fix clippy warnings for node crate (3/3)
  crates/cli/src/commands/dev/run.rs
  crates/cli/tests/whitelist_data/whitelist.json
  crates/node/src/network/handler.rs
  crates/node/src/network/module.rs
  crates/node/src/network/network_event.rs
  crates/node/src/node.rs
  crates/node/src/runtime/mod.rs
  crates/node/src/runtime/node_runtime_handler.rs
  crates/node/src/runtime/setup.rs
  crates/node/src/state_manager/mod.rs
  crates/node/src/test_utils.rs
  crates/node/tests/rpc_api.rs
  crates/node/tests/startup.rs
  crates/node/tests/state_sync.rs
Labels: code quality

#689 Add message passing helpers to modules
  crates/node/src/network/network_event_handler.rs
  crates/node/src/runtime/node_runtime.rs
Labels: enhancement

#690 Add read handle helpers to Node struct
  crates/node/src/node.rs
  crates/node/src/runtime/setup.rs
Labels: enhancement, code quality

#691 Remove hardcoded level from custom telemetry subscriber
  crates/telemetry/src/custom_subscriber.rs
Labels: bug, enhancement

#696 Avoid breaking API clients on missing data
  crates/node/src/state_manager/dag.rs
  crates/vrrb_rpc/src/rpc/api.rs
  crates/vrrb_rpc/src/rpc/server_impl.rs
Labels: bug, enhancement

#698 Refactor BootstrapConfig
  Cargo.lock
  crates/cli/src/commands/dev/run.rs
  crates/cli/src/commands/node/run.rs
  crates/cli/tests/node_cli.rs
  crates/cli/tests/whitelist_data/whitelist.json
  crates/node/src/consensus/consensus_event_handler.rs
  crates/node/src/consensus/consensus_module.rs
  crates/node/src/consensus/quorum_module.rs
  crates/node/src/network/component.rs
  crates/node/src/network/module.rs
  crates/node/src/node.rs
  crates/node/src/result.rs
  crates/node/src/runtime/handler_helpers.rs
  crates/node/src/runtime/mod.rs
  crates/node/src/runtime/node_runtime_handler.rs
  crates/node/src/runtime/setup.rs
  crates/node/src/test_utils/mock_config.rs
  crates/node/src/test_utils/mod.rs
  crates/node/src/test_utils/node_network.rs
  crates/node/src/test_utils/runtime_network.rs
  crates/primitives/src/base.rs
  crates/vrrb_config/src/bootstrap.rs
  crates/vrrb_config/src/bootstrap_quorum.rs
  crates/vrrb_config/src/lib.rs
  crates/vrrb_config/src/node_config.rs
  crates/vrrb_config/src/quorum.rs
  crates/vrrb_rpc/src/rpc/api.rs
  crates/vrrb_rpc/src/rpc/server_impl.rs
  examples/multichain.rs
Labels: code quality
