Repository versatus/versatus, pull requests merged in 2023-04, with the labels that each got.

#212 Archive unused or deprecated crates
  Cargo.toml
  crates/network/src/message.rs
  crates/syncing/Cargo.toml
  crates/syncing/src/bootstrap.rs
  crates/syncing/src/broker.rs
  crates/syncing/src/config.rs
  crates/syncing/src/context.rs
  crates/syncing/src/discovery.rs
  crates/syncing/src/error.rs
  crates/syncing/src/lib.rs
  crates/syncing/src/lrnodepool.rs
  crates/syncing/src/message.rs
  crates/syncing/src/transfer.rs
  crates/vrrb_cli/.gitignore
  crates/vrrb_cli/Cargo.toml
  crates/vrrb_cli/src/main.rs
  crates/vrrb_gui/.gitignore
  crates/vrrb_gui/Cargo.toml
  crates/vrrb_gui/src/main.rs
  crates/vrrb_lib/.gitignore
  crates/vrrb_lib/Cargo.toml
  crates/vrrb_lib/src/account.rs
  crates/vrrb_lib/src/fields.rs
  crates/vrrb_lib/src/lib.rs
  crates/vrrb_lib/src/utils.rs
Labels: bug, enhancement

#215 Implement Election runtime module
  Cargo.toml
  crates/block/Cargo.toml
  crates/block/src/block.rs
  crates/block/src/convergence_block.rs
  crates/block/src/genesis.rs
  crates/block/src/header.rs
  crates/block/src/proposal_block.rs
  crates/block/src/types.rs
  crates/cli/src/commands/node/run.rs
  crates/consensus/quorum/Cargo.toml
  crates/consensus/quorum/src/election.rs
  crates/consensus/quorum/src/lib.rs
  crates/consensus/quorum/src/quorum.rs
  crates/consensus/reward/src/reward.rs
  crates/events/Cargo.toml
  crates/events/src/lib.rs
  crates/mempool/src/mempool.rs
  crates/mempool/src/pool.rs
  crates/miner/Cargo.toml
  crates/miner/src/block_builder.rs
  crates/miner/src/conflict_resolver.rs
  crates/miner/src/lib.rs
  crates/miner/src/miner.rs
  crates/miner/src/miner_impl.rs
  crates/miner/src/miner_v1.rs
  crates/miner/src/test_helpers.rs
  crates/network/src/network.rs
  crates/node/Cargo.toml
  crates/node/src/lib.rs
  crates/node/src/node.rs
  crates/node/src/result.rs
  crates/node/src/runtime/broadcast_module.rs
  crates/node/src/runtime/dkg_module.rs
  crates/node/src/runtime/election_module.rs
  crates/node/src/runtime/farmer_harvester_module.rs
  crates/node/src/runtime/farmer_module.rs
  crates/node/src/runtime/mempool_module.rs
  crates/node/src/runtime/mining_module.rs
  crates/node/src/runtime/mod.rs
  crates/node/src/services/broadcast_controller.rs
  crates/node/tests/state_sync.rs
  crates/primitives/src/base.rs
  crates/storage/vrrbdb/src/claim_store/claim_store_rh.rs
  crates/storage/vrrbdb/src/claim_store/mod.rs
  crates/storage/vrrbdb/src/lib.rs
  crates/storage/vrrbdb/src/state_store/mod.rs
  crates/storage/vrrbdb/src/vrrbdb.rs
  crates/storage/vrrbdb/src/vrrbdb_read_handle.rs
  crates/storage/vrrbdb/tests/common.rs
  crates/storage/vrrbdb/tests/test_claim_store.rs
  crates/storage/vrrbdb/tests/test_transaction_store.rs
  crates/utils/Cargo.toml
  crates/utils/src/payload.rs
  crates/vrrb_config/src/node_config.rs
  crates/vrrb_core/Cargo.toml
  crates/vrrb_core/src/claim.rs
  crates/vrrb_core/src/helpers.rs
  crates/vrrb_core/src/keypair.rs
  crates/vrrb_core/src/ledger.rs
  crates/vrrb_core/src/txn.rs
Labels: enhancement

#232 Scaffold Election Module
  Cargo.toml
  crates/block/Cargo.toml
  crates/block/src/convergence_block.rs
  crates/block/src/proposal_block.rs
  crates/block/src/types.rs
  crates/consensus/quorum/Cargo.toml
  crates/events/Cargo.toml
  crates/events/src/lib.rs
  crates/mempool/src/mempool.rs
  crates/miner/Cargo.toml
  crates/miner/src/lib.rs
  crates/miner/src/miner.rs
  crates/network/src/network.rs
  crates/node/Cargo.toml
  crates/node/src/lib.rs
  crates/node/src/node.rs
  crates/node/src/result.rs
  crates/node/src/runtime/broadcast_module.rs
  crates/node/src/runtime/dkg_module.rs
  crates/node/src/runtime/election_module.rs
  crates/node/src/runtime/farmer_harvester_module.rs
  crates/node/src/runtime/farmer_module.rs
  crates/node/src/runtime/mempool_module.rs
  crates/node/src/runtime/mining_module.rs
  crates/node/src/runtime/mod.rs
  crates/node/src/services/broadcast_controller.rs
  crates/node/tests/state_sync.rs
  crates/storage/vrrbdb/src/claim_store/claim_store_rh.rs
  crates/storage/vrrbdb/src/claim_store/mod.rs
  crates/storage/vrrbdb/src/lib.rs
  crates/storage/vrrbdb/src/state_store/mod.rs
  crates/storage/vrrbdb/src/vrrbdb.rs
  crates/storage/vrrbdb/src/vrrbdb_read_handle.rs
  crates/storage/vrrbdb/tests/common.rs
  crates/storage/vrrbdb/tests/test_claim_store.rs
  crates/storage/vrrbdb/tests/test_transaction_store.rs
  crates/vrrb_config/src/node_config.rs
  crates/vrrb_core/Cargo.toml
  crates/vrrb_core/src/claim.rs
  crates/vrrb_core/src/helpers.rs
  crates/vrrb_core/src/lib.rs
Labels: bug, enhancement

#244 Implement http crate & indexer module
  Cargo.toml
  crates/node/Cargo.toml
  crates/node/src/node.rs
  crates/node/src/runtime/indexer_module.rs
  crates/node/src/runtime/mod.rs
  crates/vrrb_http/Cargo.toml
  crates/vrrb_http/src/http.rs
  crates/vrrb_http/src/indexer.rs
  crates/vrrb_http/src/lib.rs
Labels: enhancement

#278 Changes the way the JSON-RPC server handle is awaited such that it doesnt get interrupted by Node internal events
  crates/node/src/node.rs
  crates/node/src/runtime/mod.rs
Labels: bug

#271 Chore integrate messr into node runtime
  Cargo.toml
  crates/block/src/block.rs
  crates/block/src/convergence_block.rs
  crates/block/src/header.rs
  crates/block/src/lib.rs
  crates/block/src/proposal_block.rs
  crates/block/src/types.rs
  crates/consensus/quorum/src/quorum.rs
  crates/events/Cargo.toml
  crates/events/src/event.rs
  crates/events/src/event_data.rs
  crates/events/src/lib.rs
  crates/miner/src/block_builder.rs
  crates/miner/src/conflict_resolver.rs
  crates/miner/src/lib.rs
  crates/miner/src/miner.rs
  crates/miner/src/miner_impl.rs
  crates/miner/src/test_helpers.rs
  crates/node/Cargo.toml
  crates/node/src/lib.rs
  crates/node/src/node.rs
  crates/node/src/result.rs
  crates/node/src/runtime/broadcast_module.rs
  crates/node/src/runtime/dag_module.rs
  crates/node/src/runtime/dkg_module.rs
  crates/node/src/runtime/election_module.rs
  crates/node/src/runtime/farmer_harvester_module.rs
  crates/node/src/runtime/farmer_module.rs
  crates/node/src/runtime/harvester_module.rs
  crates/node/src/runtime/indexer_module.rs
  crates/node/src/runtime/mempool_module.rs
  crates/node/src/runtime/mining_module.rs
  crates/node/src/runtime/mod.rs
  crates/node/src/runtime/state_module.rs
  crates/node/src/runtime/swarm_module.rs
  crates/node/src/services/broadcast_controller.rs
  crates/node/src/services/scheduler.rs
  crates/node/tests/rpc_api.rs
  crates/storage/vrrbdb/src/vrrbdb.rs
  crates/storage/vrrbdb/src/vrrbdb_read_handle.rs
  crates/utils/src/payload.rs
  crates/vrrb_core/src/claim.rs
  crates/vrrb_core/src/txn.rs
  crates/vrrb_rpc/src/rpc/server.rs
  crates/vrrb_rpc/src/rpc/server_impl.rs
  crates/vrrb_rpc/tests/rpc.rs
  crates/wallet/tests/wallet_rpc_tests.rs
Labels: enhancement

#281 Ensures the API server starts and stops when stop events are issued to the proper topics
  crates/events/src/lib.rs
  crates/node/src/node.rs
  crates/node/src/runtime/broadcast_module.rs
  crates/node/src/runtime/mempool_module.rs
  crates/node/src/runtime/mod.rs
  crates/node/src/runtime/state_module.rs
  crates/node/tests/rpc_api.rs
  crates/primitives/src/environment.rs
  crates/telemetry/src/subscriber.rs
Labels: bug
