Repository versatus/versatus, pull requests merged in 2023-07, with the labels that each got.

#366 Add integral to manifest
  Cargo.toml
Labels: enhancement

#401 fix: update `keccak_hash::H256` with `patriecia::H256`
  crates/storage/lr_trie/src/inner_wrapper.rs
  crates/storage/lr_trie/src/lib.rs
  crates/storage/lr_trie/src/trie.rs
Labels: bug

#405 chore: Add `assert`s to test `vrrbdb_should_update_with_new_block()`
  crates/node/src/components/state_module.rs
  crates/node/src/lib.rs
Labels: code quality

#411 Chore rm unused node internal components
  crates/cli/src/commands/node/run.rs
  crates/events/src/event_data.rs
  crates/node/src/components/dag_module.rs
  crates/node/src/components/dkg_module.rs
  crates/node/src/components/election_module.rs
  crates/node/src/components/farmer_module.rs
  crates/node/src/components/harvester_module.rs
  crates/node/src/components/indexer_module.rs
  crates/node/src/components/mempool_module.rs
  crates/node/src/components/mining_module.rs
  crates/node/src/components/mod.rs
  crates/node/src/components/network/network_event.rs
  crates/node/src/components/scheduler.rs
  crates/node/src/components/state_module.rs
  crates/node/src/dag/mod.rs
  crates/node/src/lib.rs
  crates/node/src/network/mod.rs
  crates/node/src/network/module.rs
  crates/node/src/network/network_event.rs
  crates/node/src/network/network_handler.rs
  crates/node/src/runtime.rs
  crates/node/src/runtime_component.rs
  crates/node/src/test_utils.rs
  crates/vrrb_config/src/bootstrap_quorum.rs
  crates/vrrb_config/src/lib.rs
  crates/vrrb_config/src/node_config.rs
Labels: enhancement

#413 Remove unused gRPC API
  Cargo.toml
  buf.gen.yaml
  buf.yaml
  crates/node/Cargo.toml
  crates/vrrb_grpc/Cargo.toml
  crates/vrrb_grpc/src/gen/mod.rs
  crates/vrrb_grpc/src/gen/node_read_service.v1.rs
  crates/vrrb_grpc/src/gen/node_read_service.v1.serde.rs
  crates/vrrb_grpc/src/gen/node_read_service.v1.tonic.rs
  crates/vrrb_grpc/src/gen/node_write_service.v1.rs
  crates/vrrb_grpc/src/gen/node_write_service.v1.serde.rs
  crates/vrrb_grpc/src/gen/node_write_service.v1.tonic.rs
  crates/vrrb_grpc/src/lib.rs
  crates/vrrb_grpc/src/node_read.rs
  crates/vrrb_grpc/src/node_write.rs
  crates/vrrb_grpc/src/server.rs
  crates/vrrb_grpc/types/ts/node_read_service/v1/node_read_service_pb.d.ts
  crates/vrrb_grpc/types/ts/node_read_service/v1/node_read_service_pb.js
  crates/vrrb_grpc/types/ts/node_write_service/v1/node_write_service_pb.d.ts
  crates/vrrb_grpc/types/ts/node_write_service/v1/node_write_service_pb.js
Labels: enhancement

#408 Add initial work for WASM binary
  Cargo.toml
  crates/wasm_cli/Cargo.toml
  crates/wasm_cli/src/cli.rs
  crates/wasm_cli/src/commands/describe/mod.rs
  crates/wasm_cli/src/commands/mod.rs
  crates/wasm_cli/src/commands/validate/mod.rs
  crates/wasm_cli/src/main.rs
  crates/wasm_loader/Cargo.toml
  crates/wasm_loader/src/constants.rs
  crates/wasm_loader/src/lib.rs
  crates/wasm_loader/src/wasm_loader.rs
Labels: enhancement

#414 Restructure Node crate
  crates/events/src/event.rs
  crates/node/src/api/mod.rs
  crates/node/src/consensus/consensus_component.rs
  crates/node/src/consensus/consensus_handler.rs
  crates/node/src/consensus/consensus_module.rs
  crates/node/src/consensus/mod.rs
  crates/node/src/consensus/quorum_component.rs
  crates/node/src/consensus/quorum_handler.rs
  crates/node/src/consensus/transaction_validator.rs
  crates/node/src/dag/mod.rs
  crates/node/src/dag_module.rs
  crates/node/src/indexer_module.rs
  crates/node/src/lib.rs
  crates/node/src/mining_module.rs
  crates/node/src/network/mod.rs
  crates/node/src/network/module.rs
  crates/node/src/network/network_event_handler.rs
  crates/node/src/node.rs
  crates/node/src/runtime.rs
  crates/node/src/runtime_component.rs
  crates/node/src/state_manager/component.rs
  crates/node/src/state_manager/mod.rs
  crates/node/src/state_manager/state_handler.rs
  crates/node/src/state_manager/state_manager.rs
  crates/node/src/test_utils.rs
  crates/node/src/ui/mod.rs
  crates/vrrb_core/src/bloom.rs
Labels: enhancement, code quality

#416 Set default run attribute on Cargo.toml to run vrrb by default
  Cargo.toml
Labels: enhancement

#415 Consolidate node types
  crates/consensus/dkg_engine/src/dkg.rs
  crates/consensus/dkg_engine/src/test_utils.rs
  crates/node/src/network/module.rs
  crates/node/src/test_utils.rs
  crates/primitives/src/node.rs
  crates/vrrb_core/src/keypair.rs
  crates/vrrb_rpc/src/rpc/server.rs
  examples/minichain.rs
Labels: enhancement

#418 Update NodeConfig to enable quorum configuration
  crates/cli/src/commands/node/run.rs
  crates/node/src/network/module.rs
  crates/node/src/runtime.rs
  crates/node/src/test_utils.rs
  crates/vrrb_config/src/bootstrap.rs
  crates/vrrb_config/src/bootstrap_quorum.rs
  crates/vrrb_config/src/node_config.rs
Labels: enhancement
