Repository versatus/versatus, pull requests merged in 2023-06, with the labels that each got.

#348 chore: Add development environment shell
  shell.nix
Labels: enhancement

#355 fix: add `Security` framework from `apple_sdk`
  shell.nix
Labels: bug

#360 fix: `Event::PrecheckConvergenceBlock` match arm in `harvester_module::handle()`
  crates/node/src/runtime/harvester_module.rs
Labels: bug

#341 node gui directory rename + reputation module + stake module + node info module
  .github/ISSUE_TEMPLATE/chore_outline.yml
  .gitignore
  Makefile
  crates/cli/src/commands/node/run.rs
  crates/node/src/node.rs
  crates/node/src/runtime/mod.rs
  crates/node/tests/startup.rs
  infra/gui/.eslintrc.json
  infra/gui/.gitignore
  infra/gui/.prettierrc.json
  infra/gui/README.md
  infra/gui/app/error.tsx
  infra/gui/app/favicon.ico
  infra/gui/app/globals.css
  infra/gui/app/layout.tsx
  infra/gui/app/page.tsx
  infra/gui/app/rpc/route.ts
  infra/gui/components/AccountOverview.tsx
  infra/gui/components/AccountSelectDropdown.tsx
  infra/gui/components/ButtonBadge.tsx
  infra/gui/components/ButtonRow.tsx
  infra/gui/components/Component.tsx
  infra/gui/components/NodeInteraction.tsx
  infra/gui/components/NodeOverview.tsx
  infra/gui/components/Playground.tsx
  infra/gui/components/RPCMethodPreview.tsx
  infra/gui/components/RepRowItem.tsx
  infra/gui/components/ReputationMeter.tsx
  infra/gui/components/SignatureBuilder.tsx
  infra/gui/components/StatsBlock.tsx
  infra/gui/components/TransactionBuilder.tsx
  infra/gui/components/TxBuilder.tsx
  infra/gui/components/layout/Nav.tsx
  infra/gui/components/modules/GainsModule.tsx
  infra/gui/components/modules/NodeStatusModule.tsx
  infra/gui/components/modules/ReputationModule.tsx
  infra/gui/components/modules/StakeModule.tsx
  infra/gui/consts/system.ts
  infra/gui/contexts/NodeProvider.tsx
  infra/gui/lib/methods.ts
  infra/gui/next.config.js
  infra/gui/package.json
  infra/gui/postcss.config.js
  infra/gui/public/gradient.png
  infra/gui/public/next.svg
  infra/gui/public/vercel.svg
  infra/gui/tailwind.config.js
  infra/gui/tsconfig.json
  infra/gui/utils/functions.ts
  infra/gui/yarn.lock
  infra/ui/app/page.tsx
  infra/ui/components/Playground.tsx
  infra/ui/contexts/NodeProvider.tsx
  infra/ui/package-lock.json
Labels: enhancement

#363 Remove unused types and imports
  crates/cli/src/commands/node/run.rs
  crates/mempool/src/lib.rs
  crates/mempool/src/mempool.rs
  crates/mempool/src/pool.rs
  crates/miner/src/lib.rs
  crates/miner/src/miner_v1.rs
  crates/node/src/node.rs
  crates/node/src/runtime/dag_module.rs
  crates/node/src/runtime/harvester_module.rs
  crates/node/src/runtime/mod.rs
  crates/node/tests/startup.rs
  crates/vrrb_core/src/keypair.rs
Labels: code quality

#364 Add dyswarm to manifest
  Cargo.toml
Labels: enhancement

#362 chore: address unused `Futures`
  crates/node/src/runtime/farmer_module.rs
  crates/node/src/runtime/harvester_module.rs
  crates/node/src/runtime/mod.rs
  crates/node/src/services/scheduler.rs
Labels: code quality

#365 fix: resolve use of `Future`s in `scheduler::execute_sync_jobs()`
  crates/node/src/runtime/farmer_module.rs
  crates/node/src/runtime/mod.rs
  crates/node/src/services/scheduler.rs
Labels: bug

#370 Add RuntimeComponent abstraction
  crates/node/src/runtime/indexer_module.rs
  crates/node/src/runtime_component.rs
  crates/node/src/runtime_module.rs
Labels: enhancement, code quality

#374 Bump rust to 1.70
  rust-toolchain.toml
Labels: bug, enhancement, code quality

#376 Remove swarm module
  crates/node/src/runtime/mod.rs
  crates/node/src/runtime/swarm_module.rs
Labels: bug, enhancement, code quality

#377 Update NodeConfig to accommodate networking layer updates
  crates/cli/src/commands/node/run.rs
  crates/node/src/node.rs
  crates/node/src/test_utils.rs
  crates/primitives/Cargo.toml
  crates/primitives/src/base.rs
  crates/primitives/src/node.rs
  crates/vrrb_config/src/node_config.rs
Labels: enhancement

#378 Restructure node crate to match modular architecture paradigm
  crates/cli/src/commands/node/run.rs
  crates/events/src/event.rs
  crates/node/Cargo.toml
  crates/node/src/components/consensus.rs
  crates/node/src/components/dag_module.rs
  crates/node/src/components/dkg_module.rs
  crates/node/src/components/election_module.rs
  crates/node/src/components/farmer_module.rs
  crates/node/src/components/harvester_module.rs
  crates/node/src/components/indexer_module.rs
  crates/node/src/components/mempool_module.rs
  crates/node/src/components/mining_module.rs
  crates/node/src/components/mod.rs
  crates/node/src/components/network/mod.rs
  crates/node/src/components/network/module.rs
  crates/node/src/components/network/network_event.rs
  crates/node/src/components/network/network_handler.rs
  crates/node/src/components/scheduler.rs
  crates/node/src/components/state_module.rs
  crates/node/src/lib.rs
  crates/node/src/node.rs
  crates/node/src/node_health_report.rs
  crates/node/src/node_type.rs
  crates/node/src/result.rs
  crates/node/src/runtime.rs
  crates/node/src/runtime/blockchain_module.rs
  crates/node/src/runtime/broadcast_module.rs
  crates/node/src/runtime/reputation_module.rs
  crates/node/src/runtime_component.rs
  crates/node/src/runtime_module.rs
  crates/node/src/services/broadcast_controller.rs
  crates/node/src/services/mod.rs
  crates/node/src/test_utils.rs
  crates/utils/Cargo.toml
  crates/utils/src/payload.rs
  crates/vrrb_config/src/bootstrap.rs
  crates/vrrb_config/src/lib.rs
Labels: bug, enhancement, code quality

#375 Chore add examples dir
  Cargo.toml
  crates/events/src/event.rs
  crates/node/src/components/network/module.rs
  crates/node/src/components/network/network_handler.rs
  examples/minichain.rs
Labels: enhancement

#381 fix: `nix-shell` fails pre-commit formatting hook
  .rustfmt.toml
  infra/scripts/pre-commit.sh
Labels: code quality

#372 Initial Kontain build for VRRB compute
  tools/kontain-build/Makefile
  tools/kontain-build/README.md
Labels: enhancement, code quality

#382 Call await on Node stop method
  crates/cli/src/commands/node/run.rs
Labels: bug

#383 fix: add `rustup run nightly` to `cargo` invocation in pre-commit script
  infra/scripts/pre-commit.sh
Labels: bug

#386 Fix cleanup demo hacks
  Cargo.toml
  crates/events/src/event.rs
  crates/network/Cargo.toml
  crates/network/src/lib.rs
  crates/network/src/network.rs
  crates/network/src/packet.rs
  crates/network/src/types/config.rs
  crates/network/src/types/message.rs
  crates/network/src/types/mod.rs
  crates/node/Cargo.toml
  crates/node/src/components/network/module.rs
  crates/node/src/components/network/network_event.rs
  crates/node/src/components/network/network_handler.rs
  crates/node/src/lib.rs
  crates/node/src/node.rs
  crates/node/src/runtime.rs
  crates/node/src/test_utils.rs
  crates/primitives/src/node.rs
  crates/primitives/src/signal.rs
  examples/minichain.rs
Labels: enhancement

#387 fix: modify `Node::stop()` to return `bool` for `CancellationToken::is_cancelled()`
  crates/node/src/components/network/module.rs
  crates/node/src/node.rs
  crates/node/tests/rpc_api.rs
  crates/node/tests/startup.rs
  crates/node/tests/state_sync.rs
Labels: bug

#389 chore: Remove `network` from CI check
  .github/workflows/rust.yaml
Labels: CI

#384 chore: Add support for `HashMaps` on `vrrbdb` for tests
  crates/events/src/event.rs
  crates/node/src/components/election_module.rs
  crates/node/src/components/farmer_module.rs
  crates/node/src/components/harvester_module.rs
  crates/node/src/components/mining_module.rs
  crates/node/src/components/network/module.rs
  crates/node/src/components/scheduler.rs
  crates/node/src/components/state_module.rs
  crates/node/src/node.rs
  crates/node/src/runtime.rs
  crates/storage/vrrbdb/Cargo.toml
  crates/storage/vrrbdb/src/claim_store/claim_store_rh.rs
  crates/storage/vrrbdb/src/claim_store/mod.rs
  crates/storage/vrrbdb/src/rocksdb_adapter.rs
  crates/storage/vrrbdb/src/state_store/mod.rs
  crates/storage/vrrbdb/src/state_store/state_store_rh.rs
  crates/storage/vrrbdb/src/transaction_store/mod.rs
  crates/storage/vrrbdb/src/transaction_store/transaction_store_rh.rs
  crates/storage/vrrbdb/src/vrrbdb.rs
  crates/storage/vrrbdb/src/vrrbdb_read_handle.rs
  crates/storage/vrrbdb/tests/test_claim_store.rs
  crates/storage/vrrbdb/tests/test_state_store.rs
  crates/storage/vrrbdb/tests/test_transaction_store.rs
  crates/vrrb_grpc/Cargo.toml
  crates/vrrb_grpc/src/node_read.rs
  crates/vrrb_grpc/src/node_write.rs
  crates/vrrb_grpc/src/server.rs
  crates/vrrb_rpc/Cargo.toml
  crates/vrrb_rpc/src/rpc/server.rs
  crates/vrrb_rpc/src/rpc/server_impl.rs
  crates/vrrb_rpc/tests/rpc.rs
  crates/wallet/Cargo.toml
  crates/wallet/tests/wallet_rpc_tests.rs
Labels: code quality

#391 chore: remove unused packing macros
  crates/utils/src/packing.rs
Labels: code quality

#394 Setup Claim broadcasting on node startup
  crates/events/src/event.rs
  crates/node/src/components/harvester_module.rs
  crates/node/src/components/network/module.rs
  crates/node/src/components/network/network_handler.rs
  crates/node/src/components/state_module.rs
  crates/node/src/node.rs
  crates/node/src/result.rs
  crates/storage/vrrbdb/src/claim_store/mod.rs
  crates/storage/vrrbdb/src/rocksdb_adapter.rs
  crates/telemetry/src/subscriber.rs
  examples/minichain.rs
Labels: enhancement
