Repository versatus/versatus, pull requests merged in 2023-10, with the labels that each got.

#555 feat: strip `DKG` & add `QuorumSignatureEngine`
  .gitignore
  Cargo.toml
  crates/block/Cargo.toml
  crates/block/src/lib.rs
  crates/block/src/proposal_block.rs
  crates/block/src/types.rs
  crates/consensus/dkg_engine/src/lib.rs
  crates/consensus/signer/Cargo.toml
  crates/consensus/signer/src/engine.rs
  crates/consensus/signer/src/lib.rs
  crates/consensus/signer/src/signer.rs
  crates/events/Cargo.toml
  crates/events/src/event.rs
  crates/events/src/event_data.rs
  crates/miner/Cargo.toml
  crates/miner/src/lib.rs
  crates/miner/src/miner.rs
  crates/miner/src/test_helpers.rs
  crates/node/src/consensus/consensus_event_handler.rs
  crates/node/src/consensus/consensus_module.rs
  crates/node/src/network/module.rs
  crates/node/src/network/network_event.rs
  crates/node/src/result.rs
  crates/node/src/runtime/handler_helpers.rs
  crates/node/src/runtime/mod.rs
  crates/node/src/runtime/node_runtime.rs
  crates/node/src/runtime/node_runtime_handler.rs
  crates/node/src/state_manager/dag.rs
  crates/node/src/state_manager/manager.rs
  crates/node/src/state_manager/mod.rs
  crates/node/src/test_utils.rs
  crates/primitives/src/base.rs
  crates/vrrb_config/src/node_config.rs
Labels: enhancement

#557 feat: Pending quorum is added to harvester `Certificate`
  crates/consensus/quorum/src/quorum.rs
  crates/consensus/signer/src/engine.rs
  crates/node/src/consensus/consensus_event_handler.rs
  crates/node/src/consensus/consensus_module.rs
  crates/node/src/runtime/handler_helpers.rs
  crates/node/src/runtime/node_runtime.rs
  crates/node/src/runtime/node_runtime_handler.rs
  crates/node/src/state_manager/manager.rs
  crates/node/src/test_utils.rs
  crates/node/tests/harvesters.rs
  crates/validator/src/claim_validator.rs
  crates/vrrb_core/src/claim.rs
Labels: enhancement

#570 Complete `vesting` logic
  crates/block/src/vesting.rs
  crates/node/src/runtime/mod.rs
  crates/node/src/runtime/node_runtime.rs
  crates/storage/vrrbdb/tests/common.rs
  crates/validator/src/lib.rs
  crates/vrrb_config/src/lib.rs
Labels: enhancement

#573 Add whitelist deserializer to node CLI
  crates/cli/src/commands/node/run.rs
  crates/cli/src/lib.rs
  crates/cli/tests/node_cli.rs
  crates/cli/tests/whitelist_data/whitelist.json
  crates/node/src/test_utils.rs
  crates/primitives/src/node.rs
  crates/vrrb_config/src/bootstrap_quorum.rs
  crates/vrrb_config/src/lib.rs
  crates/vrrb_config/src/node_config.rs
Labels: enhancement

#572 fix `Quorum::check_validity`
  crates/consensus/quorum/src/quorum.rs
Labels: bug

#569 Added Prometheus Exporter to Storage agent (#565)
  crates/platform/.gitignore
  crates/storage_agent/Cargo.toml
  crates/storage_agent/src/cli.rs
  crates/storage_agent/src/commands/daemon/mod.rs
Labels: enhancement

#577 Add `keygen` CLI command
  crates/cli/src/cli.rs
  crates/cli/src/commands/keygen/mod.rs
  crates/cli/src/commands/mod.rs
  crates/cli/src/commands/node/run.rs
Labels: enhancement

#467 Ignore with reason/Fix failing Tests in CI
  .github/workflows/rust.yaml
  crates/cli/src/commands/node/run.rs
  crates/consensus/signer/src/signer.rs
  crates/node/src/runtime/mod.rs
  crates/node/src/state_manager/mod.rs
  crates/node/tests/block_processing.rs
  crates/node/tests/startup.rs
  crates/node/tests/state_sync.rs
  crates/validator/src/lib.rs
  crates/vrrb_rpc/tests/http.rs
Labels: CI

#590 Make Kademlia Peer Id workable for node operators and orchestration
  crates/cli/Cargo.toml
  crates/cli/src/commands/mod.rs
  crates/cli/src/commands/node/run.rs
  crates/cli/src/commands/utils.rs
  crates/cli/tests/node_cli.rs
  crates/cli/tests/whitelist_data/whitelist.json
  crates/node/src/network/component.rs
  crates/node/src/network/module.rs
  crates/node/src/node.rs
  crates/vrrb_config/src/node_config.rs
Labels: must-have

#583 Removes ref to udp2p, fixes #581
  Cargo.toml
  crates/events/Cargo.toml
  crates/node/Cargo.toml
  crates/vrrb_config/src/node_config.rs
  crates/vrrb_core/Cargo.toml
Labels: code quality

#582 Address compiler warnings in block crate
  crates/block/src/convergence_block.rs
  crates/block/src/lib.rs
  crates/block/src/proposal_block.rs
  crates/block/src/types.rs
  crates/block/src/vesting.rs
Labels: code quality

#593 Update `keygen` CLI to print `PublicKey` to `stdout` without debug info
  crates/cli/src/commands/keygen/mod.rs
Labels: enhancement

#589 Fix clippy warnings for miner crate
  crates/miner/src/miner.rs
  crates/miner/src/test_helpers.rs
Labels: code quality

#588 Fix clippy warnings for mempool crate
  crates/mempool/src/lib.rs
  crates/mempool/src/mempool.rs
Labels: code quality

#600 Fix clippy & build warnings in validator crate
  crates/validator/src/claim_validator.rs
  crates/validator/src/lib.rs
  crates/validator/src/txn_validator.rs
  crates/validator/src/validator_core.rs
  crates/validator/src/validator_core_manager.rs
Labels: code quality

#598 Fix clippy warnings for storage crate
  crates/storage/vrrbdb/src/rocksdb_adapter.rs
  crates/storage/vrrbdb/src/transaction_store/mod.rs
  crates/storage/vrrbdb/src/transaction_store/transaction_store_rh.rs
  crates/storage/vrrbdb/src/vrrbdb.rs
  crates/storage/vrrbdb/src/vrrbdb_read_handle.rs
  crates/storage/vrrbdb/tests/test_transaction_store.rs
Labels: code quality

#594 Fix clippy warnings for node crate (1/2)
  crates/node/src/consensus/consensus_event_handler.rs
  crates/node/src/consensus/consensus_module.rs
  crates/node/src/consensus/quorum_module.rs
  crates/node/src/network/module.rs
  crates/node/src/network/network_event.rs
  crates/node/src/runtime/handler_helpers.rs
  crates/node/src/runtime/node_runtime.rs
  crates/node/src/state_manager/dag.rs
  crates/node/src/state_manager/manager.rs
  crates/node/src/state_manager/mod.rs
  crates/node/src/test_utils.rs
Labels: code quality

#601 Fix clippy warnings in vrrb_core create
  crates/vrrb_core/src/claim.rs
  crates/vrrb_core/src/keypair.rs
  crates/vrrb_core/src/staking.rs
  crates/vrrb_core/src/transactions/transaction_kind.rs
  crates/vrrb_core/src/transactions/transfer.rs
Labels: code quality

#609 Fix clippy warnings for consensus crate
  crates/consensus/job_pool/src/pool.rs
  crates/consensus/quorum/src/lib.rs
  crates/consensus/quorum/src/quorum.rs
  crates/consensus/reward/src/reward.rs
  crates/consensus/signer/src/engine.rs
  crates/consensus/signer/src/signer.rs
Labels: code quality

#604 Fix: Update import for telemetry in examples
  examples/minichain.rs
Labels: code quality

#603 Fix clippy warnings for vrrb_rpc crate
  crates/vrrb_rpc/src/rpc/api.rs
  crates/vrrb_rpc/src/rpc/server_impl.rs
Labels: code quality

#606 Ensure genesis block contains token allocations to pre-configured addresses
  crates/block/src/block.rs
  crates/block/src/genesis.rs
  crates/block/src/lib.rs
  crates/block/src/vesting.rs
  crates/events/src/event.rs
  crates/miner/src/miner.rs
  crates/node/src/consensus/consensus_module.rs
  crates/node/src/runtime/mod.rs
  crates/node/src/runtime/node_runtime.rs
  crates/node/src/runtime/node_runtime_handler.rs
  crates/node/tests/genesis_txns.rs
  crates/node/tests/harvesters.rs
  crates/storage/vrrbdb/Cargo.toml
  crates/storage/vrrbdb/src/types.rs
  crates/storage/vrrbdb/src/vrrbdb.rs
  crates/vrrb_core/src/account.rs
Labels: must-have

#620 Remove Cargo.lock from gitignore
  .gitignore
  Cargo.lock
  crates/storage/Cargo.lock
Labels: nice-to-have
