Repository versatus/versatus, pull requests merged in 2023-12, with the labels that each got.

#688 TLS integrated for hyper webserver
  Cargo.toml
  crates/metric_exporter/Cargo.toml
  crates/metric_exporter/src/examples/metrics_example.rs
  crates/metric_exporter/src/examples/sample.pem
  crates/metric_exporter/src/examples/sample.rsa
  crates/metric_exporter/src/metric_factory.rs
Labels: enhancement

#545 Re-implement `tokio::Runtime` in the `Scheduler`
  crates/node/src/consensus/transaction_validator.rs
Labels: code quality

#700 Introduce Builder Pattern for `HttpApiServerConfig`
  Cargo.lock
  crates/vrrb_rpc/src/http/config.rs
  crates/vrrb_rpc/tests/http.rs
Labels: code quality

#705 Add `whitelist_data` to `.gitignore`
  .gitignore
  crates/cli/tests/node_cli.rs
  crates/cli/tests/whitelist_data/whitelist.json
Labels: CI

#703 Introduce Builder Pattern for `HttpApiRouterConfig`
  crates/vrrb_rpc/src/http/config.rs
  crates/vrrb_rpc/src/http/router.rs
  crates/vrrb_rpc/src/http/server.rs
Labels: code quality

#724 Address remaining clippy warnings
  crates/block/src/header.rs
  crates/cli/src/commands/dev/run.rs
  crates/cli/src/commands/faucet/mod.rs
  crates/cli/src/commands/node/run.rs
  crates/cli/src/commands/wallet/mod.rs
  crates/cli/src/commands/wallet/new.rs
  crates/consensus/job_scheduler/src/lib.rs
  crates/consensus/signer/src/engine.rs
  crates/faucet/src/faucet.rs
  crates/metric_exporter/src/metric_factory.rs
  crates/node/src/consensus/consensus_module.rs
  crates/node/src/consensus/quorum_module.rs
  crates/node/src/network/component.rs
  crates/node/src/runtime/mod.rs
  crates/node/src/state_manager/mod.rs
  crates/node/src/test_utils/mock_config.rs
  crates/node/src/test_utils/mod.rs
  crates/node/src/test_utils/node_network.rs
  crates/node/src/test_utils/runtime_network.rs
  crates/node/tests/startup.rs
  crates/primitives/src/address.rs
  crates/storage/vrrbdb/src/vrrbdb.rs
  crates/vrrb_core/src/account.rs
  crates/vrrb_rpc/src/rpc/server_impl.rs
  crates/vrrb_rpc/tests/http.rs
  crates/wallet/tests/wallet_rpc_tests.rs
  crates/wasm_runtime/src/errors.rs
  crates/wasm_runtime/src/limiting_tunables.rs
  crates/wasm_runtime/src/rust2wasm/stack_overflow.rs
  crates/wasm_runtime/src/wasm_runtime.rs
  examples/multichain.rs
Labels: code quality

#721 Add crate `compute_agent` to CI
  .github/workflows/rust.yaml
Labels: CI

#720 Add crate `wasm_runtime` to CI
  .github/workflows/rust.yaml
  crates/wasm_runtime/src/runtime_tests.rs
  crates/wasm_runtime/test_data/should_panic/stack_overflow.wasm
Labels: CI

#730 Add manual impl of `Debug` for `ServiceStatusResponse`
  crates/platform/src/services.rs
Labels: code quality

#735 Change `rpc_port` type to `u16`
  crates/service_config/src/lib.rs
Labels: bug

#727 Added initial draft of contract developer doc
  docs/DevelopingSmartContracts.md
Labels: documentation

#736 Increased rocksdb version to support recent C++ compilers
  Cargo.toml
Labels: bug

#733 Add RPC client to compute CLIs
  crates/compute_agent/src/commands/daemon/mod.rs
  crates/compute_agent/src/commands/status/mod.rs
  crates/internal_rpc/src/api.rs
  crates/internal_rpc/src/client.rs
  crates/internal_rpc/src/server.rs
  crates/internal_rpc/src/tests/mod.rs
  crates/service_config/src/lib.rs
  crates/storage_agent/src/commands/status/mod.rs
Labels: enhancement

#741 Added some code for runtime stats
  Cargo.toml
  crates/telemetry/Cargo.toml
  crates/telemetry/src/lib.rs
  crates/telemetry/src/request_stats.rs
  crates/telemetry/src/tests.rs
Labels: enhancement

#740 Compute runtime partial implementation checkpoint
  Cargo.lock
  Cargo.toml
  crates/compute_runtime/Cargo.toml
  crates/compute_runtime/src/kontain.rs
  crates/compute_runtime/src/kontain_wasm.rs
  crates/compute_runtime/src/lib.rs
  crates/compute_runtime/src/oci.rs
  crates/compute_runtime/src/oci_runc.rs
  crates/compute_runtime/src/runtime.rs
  crates/compute_runtime/src/tests.rs
  crates/compute_runtime/src/youki.rs
Labels: enhancement

#737 Fix workspace dependency tree
  .github/workflows/rust.yaml
  Cargo.lock
  Cargo.toml
  benches/Cargo.lock
  benches/Cargo.toml
  benches/README.md
  benches/src/main.rs
  crates/block/Cargo.toml
  crates/cli/Cargo.toml
  crates/cli/src/commands/dev/run.rs
  crates/cli/src/commands/node/run.rs
  crates/cli/src/lib.rs
  crates/compute_agent/Cargo.toml
  crates/compute_runtime/Cargo.toml
  crates/consensus/Cargo.toml
  crates/consensus/dkg_engine/Cargo.toml
  crates/consensus/job_pool/Cargo.toml
  crates/consensus/job_scheduler/Cargo.toml
  crates/consensus/quorum/Cargo.toml
  crates/consensus/reward/Cargo.toml
  crates/consensus/signer/Cargo.toml
  crates/consensus/vrrb_vrf/Cargo.toml
  crates/events/Cargo.toml
  crates/faucet/Cargo.toml
  crates/internal_rpc/Cargo.toml
  crates/mempool/Cargo.toml
  crates/metric_exporter/Cargo.toml
  crates/miner/Cargo.toml
  crates/node/Cargo.toml
  crates/node/src/node.rs
  crates/platform/Cargo.toml
  crates/primitives/Cargo.toml
  crates/service_config/Cargo.toml
  crates/storage/Cargo.toml
  crates/storage/utils/Cargo.toml
  crates/storage/vrrbdb/Cargo.toml
  crates/storage_agent/Cargo.toml
  crates/telemetry/Cargo.toml
  crates/telemetry/src/request_stats.rs
  crates/telemetry/src/tests.rs
  crates/utils/Cargo.toml
  crates/validator/Cargo.toml
  crates/vrrb_config/Cargo.toml
  crates/vrrb_core/Cargo.toml
  crates/vrrb_http/Cargo.toml
  crates/vrrb_rpc/Cargo.toml
  crates/wallet/Cargo.toml
  crates/wasm_cli/Cargo.toml
  crates/wasm_loader/Cargo.toml
  crates/wasm_runtime/Cargo.toml
  crates/web3_pkg/Cargo.toml
  crates/web3_pkg/src/web3_store.rs
Labels: big
