Repository versatus/versatus, pull requests merged in 2023-08, with the labels that each got.

#419 Refactor network component to account for quorum configuration
  Cargo.toml
  crates/events/src/event.rs
  crates/miner/src/test_helpers.rs
  crates/node/src/network/component.rs
  crates/node/src/network/handler.rs
  crates/node/src/network/mod.rs
  crates/node/src/network/network_event_handler.rs
  crates/node/src/runtime.rs
Labels: enhancement

#420 Add support for assigning peers to quorums
  Cargo.toml
  crates/consensus/quorum/src/quorum.rs
  crates/events/src/event.rs
  crates/events/src/event_data.rs
  crates/node/src/consensus/consensus_module.rs
  crates/node/src/consensus/mod.rs
  crates/node/src/consensus/quorum_component.rs
  crates/node/src/consensus/quorum_handler.rs
  crates/node/src/network/component.rs
  crates/node/src/network/handler.rs
  crates/node/src/network/network_event.rs
  crates/node/src/runtime.rs
  crates/primitives/src/base.rs
  crates/vrrb_config/src/bootstrap_quorum.rs
  examples/minichain.rs
Labels: enhancement

#421 Trigger DKG amongst assigned quorum members during genesis protocol
  crates/events/Cargo.toml
  crates/events/src/event.rs
  crates/node/src/consensus/consensus_module.rs
  crates/node/src/consensus/quorum_component.rs
  crates/node/src/consensus/quorum_handler.rs
  crates/node/src/network/component.rs
  crates/node/src/network/handler.rs
  crates/node/src/network/network_event.rs
  crates/node/src/network/network_event_handler.rs
  crates/node/src/node.rs
  crates/node/src/runtime.rs
  crates/vrrb_config/src/bootstrap_quorum.rs
Labels: enhancement

#426 Remove unused hooks
  .gitmodules
  .rusty-hook.toml
  Cargo.toml
Labels: code quality

#428 RPC API Scaffolding
  crates/node/src/lib.rs
  crates/node/src/node.rs
  crates/node/src/node_health_report.rs
  crates/vrrb_config/src/lib.rs
  crates/vrrb_core/src/lib.rs
  crates/vrrb_core/src/node_health_report.rs
  crates/vrrb_rpc/Cargo.toml
  crates/vrrb_rpc/src/rpc/api.rs
  crates/vrrb_rpc/src/rpc/server_impl.rs
  crates/wasm_cli/src/commands/execute/mod.rs
Labels: enhancement

#429 Define StateReader trait
  crates/node/src/lib.rs
  crates/node/src/state_reader.rs
Labels: enhancement

#430 Add StateStore trait to abstract database consumption from Node
  crates/cli/src/commands/node/run.rs
  crates/node/src/consensus/quorum_component.rs
  crates/node/src/lib.rs
  crates/node/src/node.rs
  crates/node/src/state_manager/component.rs
  crates/node/src/state_reader.rs
  crates/node/src/state_store.rs
  crates/storage/vrrbdb/src/vrrbdb.rs
Labels: enhancement

#433 Fix calls to Node::start on minichain example
  crates/node/src/data_store.rs
  crates/node/src/lib.rs
  crates/node/src/node.rs
  crates/node/src/state_manager/state_manager.rs
  crates/node/src/state_store.rs
  crates/node/src/test_utils.rs
  crates/vrrb_http/src/indexer.rs
  examples/minichain.rs
Labels: bug

#432 account param visibility changes
  crates/node/src/state_manager/mod.rs
  crates/node/src/test_utils.rs
  crates/storage/vrrbdb/src/state_store/mod.rs
  crates/storage/vrrbdb/tests/test_state_store.rs
  crates/validator/src/txn_validator.rs
  crates/vrrb_core/src/account.rs
  crates/vrrb_rpc/src/rpc/server_impl.rs
  crates/wasm_cli/Cargo.toml
Labels: enhancement

#431 initial implementation of claim rpc functions
  crates/vrrb_rpc/src/rpc/api.rs
  crates/vrrb_rpc/src/rpc/server_impl.rs
Labels: enhancement

#437 Fix leftovers from DKG Engine Refactor
  crates/consensus/dkg_engine/dkg_engine/Cargo.toml
  crates/consensus/dkg_engine/dkg_engine/src/dkg.rs
  crates/consensus/dkg_engine/dkg_engine/src/engine.rs
  crates/consensus/dkg_engine/dkg_engine/src/lib.rs
  crates/consensus/dkg_engine/dkg_engine/src/result.rs
  crates/consensus/dkg_engine/dkg_engine/src/test_utils.rs
  crates/consensus/dkg_engine/src/dkg_state.rs
  crates/consensus/dkg_engine/src/engine.rs
  crates/consensus/dkg_engine/src/lib.rs
  crates/consensus/dkg_engine/src/test_utils.rs
  crates/consensus/signer/src/signer.rs
Labels: bug

#440 Remove generics on Node and double db initialization
  Cargo.toml
  crates/cli/src/commands/node/run.rs
  crates/node/src/node.rs
  crates/node/src/runtime.rs
  crates/storage/vrrbdb/src/claim_store/mod.rs
  crates/storage/vrrbdb/src/rocksdb_adapter.rs
  crates/telemetry/src/subscriber.rs
Labels: bug
