Repository versatus/versatus, pull requests merged in 2023-09, with the labels that each got.

#446 Initial framework for compute agent and shared service config
  Cargo.toml
  crates/compute_agent/Cargo.toml
  crates/compute_agent/src/cli.rs
  crates/compute_agent/src/commands/daemon/mod.rs
  crates/compute_agent/src/commands/mod.rs
  crates/compute_agent/src/commands/status/mod.rs
  crates/compute_agent/src/main.rs
  crates/service_config/Cargo.toml
  crates/service_config/src/lib.rs
  tools/sample-configs/README.md
  tools/sample-configs/services.json
Labels: enhancement

#448 Changed branch/tag for krun/crun build
  tools/kontain-build/Makefile
Labels: bug

#450 Fixed b0rked compute CLI build
  crates/compute_agent/Cargo.toml
  crates/compute_agent/src/cli.rs
  crates/compute_agent/src/commands/mod.rs
  crates/compute_agent/src/main.rs
Labels: bug

#457 Fix `generate_claim` `Claim::new` function args
  crates/miner/src/miner.rs
Labels: bug

#443 Add `integral_db::lr_trie` & finish `jmt` integration
  Cargo.toml
  crates/node/Cargo.toml
  crates/node/src/state_manager/manager.rs
  crates/node/src/state_manager/mod.rs
  crates/node/src/test_utils.rs
  crates/storage/Cargo.toml
  crates/storage/lr_trie/Cargo.toml
  crates/storage/lr_trie/src/inner.rs
  crates/storage/lr_trie/src/inner_wrapper.rs
  crates/storage/lr_trie/src/lib.rs
  crates/storage/lr_trie/src/op.rs
  crates/storage/lr_trie/src/result.rs
  crates/storage/lr_trie/src/trie.rs
  crates/storage/src/lib.rs
  crates/storage/vrrbdb/Cargo.toml
  crates/storage/vrrbdb/src/claim_store/claim_store_rh.rs
  crates/storage/vrrbdb/src/claim_store/mod.rs
  crates/storage/vrrbdb/src/event_store/mod.rs
  crates/storage/vrrbdb/src/lib.rs
  crates/storage/vrrbdb/src/rocksdb_adapter.rs
  crates/storage/vrrbdb/src/state_store/mod.rs
  crates/storage/vrrbdb/src/state_store/state_store_rh.rs
  crates/storage/vrrbdb/src/transaction_store/mod.rs
  crates/storage/vrrbdb/src/transaction_store/transaction_store_rh.rs
  crates/storage/vrrbdb/src/vrrbdb.rs
  crates/storage/vrrbdb/src/vrrbdb_read_handle.rs
  crates/storage/vrrbdb/tests/common.rs
  crates/storage/vrrbdb/tests/test_claim_store.rs
  crates/storage/vrrbdb/tests/test_state_store.rs
  crates/storage/vrrbdb/tests/test_transaction_store.rs
  crates/validator/Cargo.toml
Labels: enhancement

#438 chore: Add social links to README
  README.md
Labels: documentation

#463 Removed deprecated `vrrb_grpc`
  .github/workflows/rust.yaml
  Cargo.toml
  crates/cli/src/commands/node/run.rs
  crates/node/src/test_utils.rs
  crates/vrrb_config/src/lib.rs
  crates/vrrb_config/src/node_config.rs
Labels: CI

#459 Fix clippy warnings
  crates/block/src/block.rs
  crates/block/src/convergence_block.rs
  crates/block/src/genesis.rs
  crates/block/src/header.rs
  crates/block/src/lib.rs
  crates/block/src/proposal_block.rs
  crates/block/src/types.rs
  crates/block/src/vesting.rs
  crates/compute_agent/src/commands/daemon/mod.rs
  crates/compute_agent/src/commands/status/mod.rs
  crates/compute_agent/src/main.rs
  crates/consensus/dkg_engine/src/engine.rs
  crates/consensus/dkg_engine/src/result.rs
  crates/consensus/dkg_engine/src/test_utils.rs
  crates/events/src/event.rs
  crates/miner/src/test_helpers.rs
  crates/node/src/consensus/consensus_component.rs
  crates/node/src/consensus/consensus_handler.rs
  crates/node/src/consensus/consensus_module.rs
  crates/node/src/consensus/quorum_module.rs
  crates/node/src/data_store.rs
  crates/node/src/mining_module.rs
  crates/node/src/network/component.rs
  crates/node/src/network/handler.rs
  crates/node/src/network/network_event.rs
  crates/node/src/network/network_event_handler.rs
  crates/node/src/node.rs
  crates/node/src/runtime.rs
  crates/node/src/state_manager/dag.rs
  crates/node/src/state_manager/handler.rs
  crates/node/src/state_manager/manager.rs
  crates/node/src/state_manager/mod.rs
  crates/node/src/state_manager/types.rs
  crates/node/src/state_manager/utils.rs
  crates/node/src/test_utils.rs
  crates/node/src/ui/mod.rs
  crates/service_config/src/lib.rs
  crates/storage/vrrbdb/src/claim_store/claim_store_rh.rs
  crates/storage/vrrbdb/src/rocksdb_adapter.rs
  crates/storage/vrrbdb/src/state_store/mod.rs
  crates/storage/vrrbdb/src/state_store/state_store_rh.rs
  crates/storage/vrrbdb/src/transaction_store/mod.rs
  crates/storage/vrrbdb/src/transaction_store/transaction_store_rh.rs
  crates/storage/vrrbdb/src/vrrbdb.rs
  crates/storage/vrrbdb/src/vrrbdb_read_handle.rs
  crates/storage_agent/src/commands/daemon/mod.rs
  crates/storage_agent/src/commands/status/mod.rs
  crates/storage_agent/src/main.rs
  crates/telemetry/src/subscriber.rs
  crates/validator/src/txn_validator.rs
  crates/validator/src/validator_core.rs
  crates/validator/src/validator_core_manager.rs
  crates/vrrb_config/src/bootstrap.rs
  crates/vrrb_config/src/node_config.rs
  crates/vrrb_core/src/transactions/transfer.rs
  crates/vrrb_http/src/indexer.rs
  crates/vrrb_rpc/src/rpc/api.rs
  crates/vrrb_rpc/src/rpc/server_impl.rs
Labels: code quality

#462 Added web3 blob store, packaging and example
  Cargo.toml
  crates/web3_pkg/Cargo.toml
  crates/web3_pkg/src/lib.rs
  crates/web3_pkg/src/pkg_tests.rs
  crates/web3_pkg/src/web3_pkg.rs
  crates/web3_pkg/src/web3_store.rs
  crates/web3_pkg/test_data/README.md
  crates/web3_pkg/test_data/pkg.json
  crates/web3_pkg/test_data/wasm_test-opt.wasm
  examples/web3-pkg.rs
  tools/kontain-build/make-web3-package
Labels: enhancement

#485 Add missing conditional to `consolidate_update_args`
  crates/node/src/state_manager/mod.rs
  crates/node/src/state_manager/utils.rs
Labels: bug

#493 Fix `generate_transfer_digest_vec` imports
  crates/node/src/runtime/node_runtime.rs
  crates/node/src/test_utils.rs
Labels: bug

#494 bug: Remove GRPC from builder & config
  crates/cli/src/commands/node/run.rs
  crates/node/src/test_utils.rs
  crates/vrrb_config/src/node_config.rs
Labels: bug

#499 Fix: RocksDB `column_family` error
  crates/storage/vrrbdb/src/rocksdb_adapter.rs
Labels: bug
