Repository versatus/versatus, pull requests merged in 2024-01, with the labels that each got.

#745 RocksDB and examples fixes
  Cargo.lock
  crates/platform/Cargo.toml
  crates/storage/vrrbdb/Cargo.toml
  crates/web3_pkg/Cargo.toml
Labels: bug

#746 Added subcommand to WASM CLI to publish contract to IPFS
  Cargo.lock
  Cargo.toml
  crates/wasm_cli/Cargo.toml
  crates/wasm_cli/src/cli.rs
  crates/wasm_cli/src/commands/mod.rs
  crates/wasm_cli/src/commands/publish/mod.rs
  crates/wasm_cli/src/main.rs
Labels: enhancement

#747 Added Command Line manual for versatus-wasm
  docs/CommandReferenceWasm.md
Labels: documentation

#742 Added the code for pinning object, check if object is pinned and to read object
  Cargo.toml
  crates/compute_agent/Cargo.toml
  crates/internal_rpc/Cargo.toml
  crates/internal_rpc/src/api.rs
  crates/internal_rpc/src/server.rs
  crates/internal_rpc/src/tests/mod.rs
  crates/metric_exporter/Cargo.toml
  crates/node/Cargo.toml
  crates/node/src/test_utils/mock_config.rs
  crates/storage_agent/Cargo.toml
  crates/vrrb_config/src/lib.rs
  crates/web3_pkg/src/web3_store.rs
Labels: enhancement

#750 Bug fix, fixed wrongly initiated arguments path for prometheus tls
  crates/compute_agent/src/commands/daemon/mod.rs
  crates/storage_agent/src/commands/daemon/mod.rs
Labels: bug

#744 Wrap magic numbers and strings in constants
  crates/node/src/test_utils/mod.rs
Labels: code quality

#755 Feat resolve dns ipfsclient
  Cargo.toml
  crates/internal_rpc/src/api.rs
  crates/storage_agent/src/commands/data_retrieval/mod.rs
  crates/wasm_cli/src/commands/publish/mod.rs
  crates/web3_pkg/Cargo.toml
  crates/web3_pkg/src/web3_store.rs
Labels: enhancement

#754 Add job queue, server RPCs and client CLI to `compute_agent`
  Cargo.lock
  crates/compute_agent/Cargo.toml
  crates/compute_agent/src/cli.rs
  crates/compute_agent/src/commands/compute_job/job_status.rs
  crates/compute_agent/src/commands/compute_job/mod.rs
  crates/compute_agent/src/commands/compute_job/queue_job.rs
  crates/compute_agent/src/commands/daemon/mod.rs
  crates/compute_agent/src/commands/mod.rs
  crates/compute_agent/src/main.rs
  crates/compute_runtime/src/lib.rs
  crates/compute_runtime/src/runtime.rs
  crates/compute_runtime/src/tests.rs
  crates/internal_rpc/Cargo.toml
  crates/internal_rpc/src/api.rs
  crates/internal_rpc/src/job_queue/channel.rs
  crates/internal_rpc/src/job_queue/job.rs
  crates/internal_rpc/src/job_queue/mod.rs
  crates/internal_rpc/src/lib.rs
  crates/internal_rpc/src/server.rs
  crates/internal_rpc/src/tests/mod.rs
  crates/storage_agent/src/commands/daemon/mod.rs
Labels: enhancement

#760 Increased default memory maximum for WASM
  crates/wasm_runtime/src/limiting_tunables.rs
Labels: enhancement

#762 Evaluate WASM runtime execution `Result` after metering is checked
  Cargo.lock
  crates/wasm_runtime/src/wasm_runtime.rs
Labels: bug

#763 Increase meter limit for tests
  crates/wasm_runtime/src/runtime_tests.rs
Labels: bug
