Repository versatus/versatus, pull requests merged in 2024-02, with the labels that each got.

#766 Only report contract errors if `stderr` is non-empty
  crates/wasm_cli/src/commands/execute/mod.rs
Labels: bug

#767 Update is_pinned Function Signature and Address Clippy Suggestions
  Cargo.toml
  crates/internal_rpc/src/api.rs
  crates/internal_rpc/src/server.rs
  crates/storage_agent/src/commands/pin_status/mod.rs
  crates/wasm_cli/src/commands/pkginfo/mod.rs
  crates/wasm_cli/src/commands/publish/mod.rs
  crates/web3_pkg/src/web3_store.rs
Labels: code quality

#772 Rename `inputs` field on `ServiceJob` to `compute_inputs`
  crates/internal_rpc/src/job_queue/job.rs
Labels: code quality

#773 Update the error message returned when `CidManifest` fails to parse
  crates/compute_runtime/src/runtime.rs
Labels: code quality

#774 Make cost function for `wasm_runtime` zero
  crates/wasm_runtime/src/metering.rs
Labels: code quality

#775 Update default tunables to 1GB max limit
  crates/wasm_runtime/src/limiting_tunables.rs
Labels: bug

#778 Set mem limit to 64 and added checks
  Cargo.lock
  crates/wasm_cli/src/commands/describe/mod.rs
  crates/wasm_cli/src/commands/pkginfo/mod.rs
  crates/wasm_cli/src/commands/publish/mod.rs
  crates/wasm_cli/src/commands/validate/mod.rs
  crates/wasm_loader/Cargo.toml
  crates/wasm_loader/src/constants.rs
  crates/wasm_loader/src/lib.rs
  crates/wasm_loader/src/wasm_loader.rs
  crates/wasm_runtime/src/limiting_tunables.rs
  crates/wasm_runtime/src/runtime_tests.rs
  crates/wasm_runtime/src/wasm_runtime.rs
Labels: bug

#780 Fixed failing test case
  crates/wasm_loader/src/lib.rs
  crates/wasm_loader/test_data/simple-versatus.wasm
Labels: bug

#781 Added annotations fields to web3-pkg test JSON
  crates/web3_pkg/test_data/pkg.json
Labels: bug

#779 fix warnings & formatting, add missing crates to CI
  .github/workflows/rust.yaml
  Cargo.lock
  crates/cli/src/commands/dev/mod.rs
  crates/cli/src/commands/node/mod.rs
  crates/compute_agent/src/commands/daemon/mod.rs
  crates/compute_runtime/src/runtime.rs
  crates/compute_runtime/src/tests.rs
  crates/consensus/job_pool/src/task.rs
  crates/consensus/job_scheduler/src/lib.rs
  crates/consensus/quorum/src/lib.rs
  crates/consensus/signer/src/signer.rs
  crates/consensus/vrrb_vrf/src/lib.rs
  crates/internal_rpc/src/tests/mod.rs
  crates/mempool/src/lib.rs
  crates/mempool/src/mempool.rs
  crates/metric_exporter/src/examples/metrics_example.rs
  crates/miner/src/lib.rs
  crates/miner/src/test_helpers.rs
  crates/node/src/consensus/mod.rs
  crates/node/src/indexer_module.rs
  crates/node/src/network/mod.rs
  crates/node/src/runtime/mod.rs
  crates/node/src/state_manager/dag.rs
  crates/node/src/state_manager/manager.rs
  crates/node/src/state_manager/mod.rs
  crates/node/src/test_utils/mock_config.rs
  crates/node/src/test_utils/mod.rs
  crates/node/src/test_utils/node_network.rs
  crates/node/src/test_utils/runtime_network.rs
  crates/node/tests/block_processing.rs
  crates/node/tests/genesis_rewards.rs
  crates/node/tests/harvesters.rs
  crates/node/tests/startup.rs
  crates/storage/vrrbdb/src/lib.rs
  crates/storage/vrrbdb/tests/common.rs
  crates/storage/vrrbdb/tests/test_transaction_store.rs
  crates/validator/src/lib.rs
  crates/vrrb_core/src/claim.rs
  crates/vrrb_core/src/keypair.rs
  crates/vrrb_core/src/staking.rs
  crates/vrrb_core/src/transactions/transaction.rs
  crates/vrrb_http/src/http.rs
  crates/vrrb_http/src/indexer.rs
  crates/vrrb_rpc/tests/rpc.rs
  crates/wallet/src/lib.rs
  crates/wasm_cli/src/commands/pkginfo/mod.rs
  crates/wasm_cli/src/commands/publish/mod.rs
  crates/wasm_runtime/src/errors.rs
  crates/wasm_runtime/src/wasm_runtime.rs
  crates/web3_pkg/src/web3_store.rs
Labels: CI, code quality
